# Generated by Django 6.0.3 on 2026-04-14 12:09

import importlib

from django.db import migrations, models


def _load_plateforme_flat_view_helpers():
    module = importlib.import_module('patients.migrations.0007_ensure_plateforme_flat_view')
    return module.ensure_plateforme_flat_view, module.drop_plateforme_flat_view


ensure_plateforme_flat_view, drop_plateforme_flat_view = _load_plateforme_flat_view_helpers()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patient_id_alter_patientformfield_id_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_plateforme_flat_view, ensure_plateforme_flat_view),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientformfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patientformtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RunPython(ensure_plateforme_flat_view, drop_plateforme_flat_view),
    ]
