# Generated by Django 5.2.13 on 2026-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_patient_id_alter_patientformfield_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='icc_charlson',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score Charlson'),
        ),
    ]
