# Generated by Django 5.2.13 on 2026-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_patient_icc_charlson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='biologie_dfg_mdrd_ml_min_1_73m2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='comorbidite_antecedents_medicaments_nephrotoxiques',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='comorbidite_exposition_toxique',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='devenir_delai_deces_jours',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dialyse_acces_admission_fav',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dialyse_acces_admission_femoral',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dialyse_acces_admission_peritoneale',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dialyse_acces_admission_tunnelise',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dialyse_jours_entre_catheter_et_fav',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_complications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_connaissance_pratique_dialyse',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_dietetique',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_soins_acces_vasculaire',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_surveillance_poids_fluides',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education_traitements_associes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='immunologie_transfusion_immunisation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='transplantation_bilan_pretransplantation',
        ),
        migrations.AlterField(
            model_name='patient',
            name='icc_charlson',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
