# Generated by Django 5.2.13 on 2026-05-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_patient_irc_duree_suivi_predialytique_mois'),
        ('patients', '0014_remove_patient_biologie_dfg_mdrd_ml_min_1_73m2_and_more'),
    ]

    operations = [
    ]
