import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'app_language';

const translations = {
  fr: {
    languageName: 'Français',
    profile: 'Profil',
    profileTitle: 'Profil utilisateur',
    role: 'Rôle',
    telephone: 'Téléphone',
    changePasswordTitle: 'Modifier votre mot de passe',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le nouveau mot de passe',
    currentPasswordHelper: 'Veuillez entrer votre mot de passe actuel pour confirmer votre identité',
    newPasswordHelper: 'Minimum 8 caractères',
    confirmPasswordHelper: 'Entrez le même mot de passe que ci-dessus',
    submitPassword: 'Modifier le mot de passe',
    cancel: 'Annuler',
    languageSectionTitle: 'Langue de l’interface',
    languageSectionDescription: 'Choisissez la langue d’affichage de la plateforme.',
    languageLabel: 'Langue',
    french: 'Français',
    english: 'Anglais',
    languageBadge: 'Langue active',
    landingTitle: 'Bienvenue dans votre espace santé',
    landingSubtitle: "Ouvrez votre compte sécurisé pour accéder à vos dossiers patients, vos analyses et vos outils de suivi médical.",
    landingCTA: 'Commencer',
    dashboard: 'Tableau de bord',
    patients: 'Patients',
    aiAnalysis: 'Analyse IA',
    monitor: 'Monitor',
    dashboardTitle: 'Tableau de bord',
    dashboardSubtitle: 'Gestion hiérarchisée des utilisateurs, confirmation des opérations sensibles et accès limité aux rôles autorisés.',
    dashboardOpenMonitor: 'Ouvrir le Patient Monitoring Board',
    dashboardVisibleAccounts: 'Comptes visibles',
    dashboardVisibleAccountsDesc: 'Selon votre périmètre d’accès.',
    dashboardActiveAccounts: 'Actifs',
    dashboardActiveAccountsDesc: 'Comptes utilisables immédiatement.',
    dashboardInactiveAccounts: 'Inactifs',
    dashboardInactiveAccountsDesc: 'Comptes suspendus ou revus.',
    dashboardProfessors: 'Professeurs',
    dashboardProfessorsDesc: 'Nombre de professeurs gérés.',
    dashboardResidents: 'Résidents',
    dashboardResidentsDesc: 'Nombre de résidents gérés.',
    dashboardRolesLoaded: 'Rôles chargés',
    dashboardRolesLoadedDesc: 'Profils disponibles dans le système.',
    dashboardSessionActive: 'Session active',
    dashboardConnectedProfile: 'Profil connecté',
    dashboardFullName: 'Nom complet',
    dashboardAccessLimit: 'Accès limité au périmètre autorisé.',
    dashboardDashboardTitle: 'Gestion des comptes',
    dashboardDashboardSubtitle: 'Les super administrateurs et chefs de service gèrent uniquement les Professeurs et Résidents. Saisissez la confirmation pour créer, modifier ou révoquer un compte.',
    dashboardUserManagement: 'Gestion des comptes',
    dashboardUserManagementDesc: 'Les super administrateurs et chefs de service gèrent uniquement les Professeurs et Résidents. Saisissez la confirmation pour créer, modifier ou révoquer un compte.',
    dashboardUserEmail: 'Email',
    dashboardUserPhone: 'Téléphone',
    dashboardUserLastName: 'Nom',
    dashboardUserFirstName: 'Prénom',
    dashboardUserRole: 'Rôle',
    dashboardUserStatus: 'Statut',
    dashboardUserSelectRole: 'Sélectionner',
    dashboardUserActive: 'Actif',
    dashboardUserInactive: 'Inactif',
    dashboardSaveConfirmationPassword: "Mot de passe de validation",
    dashboardCreatePassword: 'Mot de passe du nouveau compte',
    dashboardNewPassword: 'Nouveau mot de passe',
    dashboardCreateButton: 'Créer',
    dashboardUpdateButton: 'Modifier',
    dashboardResetButton: 'Réinitialiser',
    patientsManagementTitle: 'Gestion des données patients',
    patientsListTitle: 'Liste des patients',
    patientsImportHint: "L'import est autorisé, mais la validation reste réservée aux administrateurs et chefs de service",
    patientsReservedHint: 'Réservé aux administrateurs et chefs de service',
    patientsDataStatus: "Statut d'insertion des données",
    patientsImportPendingSince: 'Les données importées sont en attente de validation depuis',
    patientsValidateImport: "Valider l'insertion",
    patientsRejectImport: "Refuser l'insertion",
    patientsImportRequiredInfo: "Un chef de service ou un administrateur doit valider l'insertion pour que les données soient prises en compte.",
    patientsImportValidated: 'Insertion validée par',
    patientsImportRejected: 'Insertion refusée par',
    patientsImporting: 'Import...',
    patientsDeleting: 'Suppression...',
    patientsApply: 'Appliquer',
    patientsReset: 'Réinitialiser',
    patientsHideExtraRows: 'Masquer lignes supplémentaires',
    patientsModify: 'Modifier',
    patientsDelete: 'Supprimer',
    patientsNoPatientFound: 'Aucun patient trouvé.',
    patientsSearchName: 'Nom',
    patientsSearchNamePlaceholder: 'Nom du patient',
    patientsSearchId: 'ID patient',
    patientsSearchSex: 'Sexe',
    patientsAgeMin: 'Age min',
    patientsAgeMax: 'Age max',
    patientsSearchAll: 'Tous',
    patientsSearchMale: 'Homme',
    patientsSearchFemale: 'Femme',
    patientsSearchUnknown: 'Inconnu',
    patientsSearchOther: 'Autre',
    patientsImportExcel: 'Importer Excel',
    patientsFilter: 'Filtrer',
    patientsClearImported: 'Vider donnees importees',
    patientsShowAllRows: 'Afficher toutes les lignes',
    patientsSearchPlaceholder: 'Rechercher un utilisateur...',
    patientsSearchResults: 'Résultats',
    patientsNoMatch: 'Aucun patient correspondant.',
    monitorTitle: 'Patient Monitoring Board',
    monitorSubtitle: 'Vue centrée sur un patient unique, combinant informations cliniques, événements du dossier et résultats d’intelligence artificielle.',
    monitorPatientChip: 'Suivi patient',
    monitorClinicalChip: 'Audit clinique',
    monitorSearchSectionTitle: 'Recherche patient',
    monitorSearchTitle: 'Accès direct au dossier',
    monitorSearchPlaceholder: 'Nom, prénom ou identifiant',
    monitorSearchResults: 'Résultats',
    monitorNoMatch: 'Aucun patient correspondant.',
    monitorLoading: 'Chargement des données...',
    monitorSelectPatientTitle: 'Sélectionnez un patient',
    monitorSelectPatientSubtitle: 'Lancez une recherche par identifiant ou nom pour ouvrir le board patient avec son historique clinique et ses analyses IA.',
    monitorPatientFile: 'Dossier patient',
    monitorRiskLabel: 'Risque IA 1 an',
    monitorHistoryTitle: 'Historique des actions',
    monitorDeleteHistory: 'Supprimer de mon historique',
    monitorAITitle: 'Analyse IA',
    monitorModelLabel: 'Modèle',
    monitorScoreLabel: 'Score',
    monitorRiskLevelLabel: 'Niveau de risque',
    monitorInterpretationLabel: 'Interprétation',
    monitorFactorsLabel: 'Facteurs principaux',
    monitorNoPrediction: 'Aucune prédiction IA n’a encore été lancée pour ce patient.',
    monitorOpenAI: 'Ouvrir l’analyse IA',
    monitorNoEvents: 'Aucun événement disponible pour ce patient.',
    monitorPerformedBy: 'Effectué par',
    monitorNoRecommendation: 'Aucune recommandation détaillée disponible.',
    monitorNoFactors: 'Non renseignés.',
    monitorPatientIdAbsent: 'Identifiant absent',
    monitorNoClinicalData: 'Dossier clinique',
    monitorOpenedRecordBy: 'Ouverture du dossier patient par',
    monitorPatientId: 'Identifiant patient',
    monitorFullName: 'Nom complet',
    monitorAge: 'Âge',
    monitorSex: 'Sexe',
    monitorDisease: 'Maladie',
    monitorInclusionStatus: 'Statut inclusion',
    monitorConsent: 'Consentement',
    monitorLastUpdate: 'Dernière mise à jour',
    monitorPatientSaved: 'enregistré dans la plateforme.',
    monitorClinicalDataUpdated: 'Les données cliniques ont été mises à jour.',
    monitorPatientIdMissingShort: 'ID non renseigné',
    monitorActionPatientCreate: 'Création du dossier patient',
    monitorActionPatientUpdate: 'Mise à jour du dossier patient',
    monitorActionPatientDelete: 'Suppression du dossier patient',
    monitorActionPatientConsult: 'Dossier patient consulté',
    monitorActionPatientLatestUpdate: 'Dernière mise à jour',
    monitorActionPrediction: 'Prédiction IA',
    notifications: 'Notifications',
    logout: 'Déconnexion',
    appName: 'AI Néphro',
    appShortName: 'AI Néphro',
    profileUser: 'Profil utilisateur',
    profileTitleSmall: 'Profil utilisateur',
    auditCardTitle: 'Historique d’audit système',
    auditCardDescription: 'Actions enregistrées dans le système et visibles selon le rôle connecté.',
    auditViewerHint: 'Visible pour Super Administrateur et Chef de service',
    auditLoading: 'Chargement de l’historique…',
    auditEmpty: 'Aucune action enregistrée pour le moment.',
    auditError: 'Impossible de charger l’historique d’audit.',
    auditShowDetails: 'Voir détails',
    auditHideEntry: 'Masquer',
    auditDetails: 'Détails',
    auditNoDetails: 'Aucun détail supplémentaire.',
    auditOldValue: 'Ancienne valeur',
    auditNewValue: 'Nouvelle valeur',
    loginTitle: 'Connexion',
    loginSubtitle: 'Connectez-vous pour continuer vers l’espace patient sécurisé.',
    loginButton: 'Connexion',
    emailLabel: 'Email',
    emailPlaceholder: 'admin@hopital.com',
    passwordLabel: 'Mot de passe',
    passwordPlaceholder: '••••••••••••••',
    loginErrorInvalid: 'Identifiants incorrects. Veuillez réessayer.',
    unauthorizedTitle: 'Accès non autorisé',
    unauthorizedMessage: 'Votre rôle ne dispose pas des permissions nécessaires pour afficher cette page.',
    unauthorizedBack: 'Retour au tableau de bord',
    auditActionCreateUser: 'Création d’utilisateur',
    auditActionUpdateUser: 'Modification d’utilisateur',
    auditActionDeleteUser: 'Suppression d’utilisateur',
    auditActionViewPassword: 'Consultation du hash de mot de passe',
    auditActionChangePassword: 'Modification du mot de passe',
    currentPasswordError: 'Veuillez entrer votre mot de passe actuel',
    newPasswordError: 'Veuillez entrer un nouveau mot de passe',
    passwordLengthError: 'Le mot de passe doit contenir au moins 8 caractères',
    passwordMismatchError: 'Les mots de passe ne correspondent pas',
    passwordSameError: 'Le nouveau mot de passe doit être différent du mot de passe actuel',
    passwordSuccess: 'Mot de passe modifié avec succès !',
    passwordGenericError: 'Erreur lors de la modification du mot de passe',
  },
  en: {
    languageName: 'English',
    profile: 'Profile',
    profileTitle: 'User profile',
    role: 'Role',
    telephone: 'Phone',
    changePasswordTitle: 'Change your password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    currentPasswordHelper: 'Enter your current password to confirm your identity',
    newPasswordHelper: 'Minimum 8 characters',
    confirmPasswordHelper: 'Enter the same password as above',
    submitPassword: 'Change password',
    cancel: 'Cancel',
    landingTitle: 'Welcome to your health workspace',
    landingSubtitle: 'Open your secure account to access patient records, analyses and monitoring tools.',
    landingCTA: 'Get started',
    languageSectionTitle: 'Interface language',
    languageSectionDescription: 'Choose the display language for the platform.',
    languageLabel: 'Language',
    french: 'French',
    english: 'English',
    languageBadge: 'Active language',
    dashboard: 'Dashboard',
    patients: 'Patients',
    aiAnalysis: 'AI Analysis',
    monitor: 'Monitor',
    dashboardTitle: 'Dashboard',
    dashboardSubtitle: 'Hierarchical management of users, confirmation of sensitive operations, and restricted access by authorized roles.',
    dashboardOpenMonitor: 'Open Patient Monitoring Board',
    patientsManagementTitle: 'Patient data management',
    patientsImportExcel: 'Import Excel',
    patientsFilter: 'Filter',
    patientsClearImported: 'Clear imported data',
    patientsShowAllRows: 'Show all rows',
    patientsSearchPlaceholder: 'Search a user...',
    patientsSearchResults: 'Results',
    patientsNoMatch: 'No matching patient.',
    monitorTitle: 'Patient Monitoring Board',
    monitorSubtitle: 'Patient-centric view combining clinical information, chart events, and artificial intelligence results.',
    monitorPatientChip: 'Patient follow-up',
    monitorClinicalChip: 'Clinical audit',
    monitorSearchSectionTitle: 'Patient search',
    monitorSearchTitle: 'Direct access to the record',
    monitorSearchPlaceholder: 'Name, first name or ID',
    monitorSearchResults: 'Results',
    monitorNoMatch: 'No matching patient.',
    monitorLoading: 'Loading data...',
    monitorSelectPatientTitle: 'Select a patient',
    monitorSelectPatientSubtitle: 'Search by ID or name to open the patient board with clinical history and AI analyses.',
    monitorPatientFile: 'Patient record',
    monitorRiskLabel: '1-year AI risk',
    monitorHistoryTitle: 'Activity history',
    monitorDeleteHistory: 'Remove from my history',
    monitorAITitle: 'AI analysis',
    monitorModelLabel: 'Model',
    monitorScoreLabel: 'Score',
    monitorRiskLevelLabel: 'Risk level',
    monitorInterpretationLabel: 'Interpretation',
    monitorFactorsLabel: 'Key factors',
    monitorNoPrediction: 'No AI prediction has been run for this patient yet.',
    monitorOpenAI: 'Open AI analysis',
    monitorNoEvents: 'No events available for this patient.',
    monitorPerformedBy: 'Performed by',
    monitorNoRecommendation: 'No detailed recommendation available.',
    monitorNoFactors: 'Not provided.',
    monitorPatientIdAbsent: 'ID absent',
    monitorNoClinicalData: 'Clinical record',
    monitorOpenedRecordBy: 'Patient record opened by',
    monitorPatientId: 'Patient ID',
    monitorFullName: 'Full name',
    monitorAge: 'Age',
    monitorSex: 'Sex',
    monitorDisease: 'Disease',
    monitorInclusionStatus: 'Inclusion status',
    monitorConsent: 'Consent',
    monitorLastUpdate: 'Last update',
    monitorPatientSaved: 'saved in the platform.',
    monitorClinicalDataUpdated: 'Clinical data has been updated.',
    monitorPatientIdMissingShort: 'ID not provided',
    monitorActionPatientCreate: 'Patient record creation',
    monitorActionPatientUpdate: 'Patient record update',
    monitorActionPatientDelete: 'Patient record deletion',
    monitorActionPatientConsult: 'Patient record viewed',
    monitorActionPatientLatestUpdate: 'Latest update',
    monitorActionPrediction: 'AI prediction',
    notifications: 'Notifications',
    logout: 'Logout',
    appName: 'AI Nephro',
    appShortName: 'AI Nephro',
    profileUser: 'User profile',
    profileTitleSmall: 'User profile',
    auditCardTitle: 'System audit history',
    auditCardDescription: 'Recorded actions in the system, shown according to the connected role.',
    auditViewerHint: 'Visible to Super Administrator and Service Head',
    auditLoading: 'Loading audit history…',
    auditEmpty: 'No actions recorded yet.',
    auditError: 'Unable to load the audit history.',
    auditShowDetails: 'Show details',
    auditHideEntry: 'Hide',
    auditDetails: 'Details',
    auditNoDetails: 'No additional details available.',
    auditOldValue: 'Old value',
    auditNewValue: 'New value',
    loginTitle: 'Sign in',
    loginSubtitle: 'Sign in to continue to the secure patient area.',
    loginButton: 'Sign in',
    emailLabel: 'Email',
    emailPlaceholder: 'admin@hospital.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••••••••',
    loginErrorInvalid: 'Invalid credentials. Please try again.',
    unauthorizedTitle: 'Unauthorized',
    unauthorizedMessage: 'Your role does not have the required permissions to view this page.',
    unauthorizedBack: 'Back to dashboard',
    auditActionCreateUser: 'User creation',
    auditActionUpdateUser: 'User update',
    auditActionDeleteUser: 'User deletion',
    auditActionViewPassword: 'Password hash viewed',
    auditActionChangePassword: 'Password changed',
    currentPasswordError: 'Please enter your current password',
    newPasswordError: 'Please enter a new password',
    passwordLengthError: 'Password must be at least 8 characters long',
    passwordMismatchError: 'Passwords do not match',
    passwordSameError: 'The new password must be different from the current password',
    passwordSuccess: 'Password changed successfully!',
    passwordGenericError: 'Error while changing password',
  },
};

const LanguageContext = createContext({
  language: 'fr',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key) => key,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'en' ? 'en' : 'fr';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage === 'en' ? 'en' : 'fr');
  };

  const toggleLanguage = () => {
    setLanguageState((current) => (current === 'fr' ? 'en' : 'fr'));
  };

  const t = useMemo(() => {
    return (key) => translations[language]?.[key] || translations.fr[key] || key;
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, toggleLanguage, t }), [language, t]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => useContext(LanguageContext);
