# Generated by hand to change AuditLog.action to TextField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_auditlog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.TextField(),
        ),
    ]
