# Generated by Django 5.2.13 on 2026-05-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_alter_action_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiddenauditlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
