from django.urls import path

from .views import (
    PatientBulkPurgeView,
    PatientDynamicColumnsCleanupView,
    PatientDetailView,
    PatientExportExcelView,
    PatientPreprocessAnalyzeView,
    PatientPreprocessHealthView,
    PatientPreprocessReplayView,
    PatientPreprocessStatusView,
    PatientPreprocessSessionView,
    PatientPreprocessRowsView,
    PatientPreprocessRowDetailView,
    PatientPreprocessExportView,
    PatientPreprocessIntegrateView,
    PatientImportExcelView,
    PatientListCreateView,
    PatientPlateformeFlatView,
    PatientSchemaView,
)

urlpatterns = [
    path('', PatientListCreateView.as_view(), name='patient_list_create'),
    path('purge/', PatientBulkPurgeView.as_view(), name='patient_bulk_purge'),
    path('cleanup-dynamic-columns/', PatientDynamicColumnsCleanupView.as_view(), name='patient_cleanup_dynamic_columns'),
    path('preprocess/health/', PatientPreprocessHealthView.as_view(), name='patient_preprocess_health'),
    path('preprocess/analyze/', PatientPreprocessAnalyzeView.as_view(), name='patient_preprocess_analyze'),
    path('preprocess/<str:preprocess_id>/status/', PatientPreprocessStatusView.as_view(), name='patient_preprocess_status'),
    path('preprocess/<str:session_id>/', PatientPreprocessSessionView.as_view(), name='patient_preprocess_session'),
    path('preprocess/<str:session_id>/replay/', PatientPreprocessReplayView.as_view(), name='patient_preprocess_replay'),
    path('preprocess/<str:session_id>/rows/', PatientPreprocessRowsView.as_view(), name='patient_preprocess_rows'),
    path('preprocess/<str:session_id>/rows/<int:row_index>/', PatientPreprocessRowDetailView.as_view(), name='patient_preprocess_row_detail'),
    path('preprocess/<str:session_id>/export/', PatientPreprocessExportView.as_view(), name='patient_preprocess_export'),
    path('preprocess/<str:session_id>/integrate/', PatientPreprocessIntegrateView.as_view(), name='patient_preprocess_integrate'),
    path('<int:pk>/', PatientDetailView.as_view(), name='patient_detail'),
    path('import/', PatientImportExcelView.as_view(), name='patient_import_excel'),
    path('import-excel/', PatientImportExcelView.as_view(), name='patient_import_excel_legacy'),
    path('export/', PatientExportExcelView.as_view(), name='patient_export_excel'),
    path('flat/', PatientPlateformeFlatView.as_view(), name='patient_flat_list'),
    path('schema/', PatientSchemaView.as_view(), name='patient_schema'),
]
